name: Dispatch NPM Release

on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        description: Module (common | react)
        options:
          - common
          - react

      build_mode:
        type: choice
        description: Build mode (patch | minor | major | prepatch | preminor | premajor | prerelease)
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

env:
  MODULE: ${{ github.event.inputs.module }}
  BUILD_MODE: ${{ github.event.inputs.build_mode }}

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          registry-url: "https://registry.npmjs.org"

      - name: Setup Git identity
        run: |
          git config user.name "gennex"
          git config user.email "anhtai741981@gmail.com"

      - name: Verify Inputs
        run: |
          echo "MODULE: $MODULE"
          echo "BUILD_MODE: $BUILD_MODE"

      - name: Enable Yarn (Corepack)
        run: |
          corepack enable
          corepack prepare yarn@4.10.3 --activate

      - name: Install dependencies
        run: |
          yarn install

      - name: Build + Version module
        run: |
          echo "Cleaning old build..."
          rm -rf packages/$MODULE/dist

          echo "Compiling module..."
          yarn workspace @gennex/eslint-$MODULE compile

          echo "Versioning module..."
          yarn workspace @gennex/eslint-$MODULE version $BUILD_MODE

      - name: Publish package to npm registry
        run: |
          cd packages/$MODULE

          npm_tag=$(case $BUILD_MODE in
            patch|minor|major) echo "latest" ;;
            prepatch|preminor|premajor|prerelease) echo "next" ;;
          esac)

          npm publish --access public --tag $npm_tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Push updated version back to repository
        run: |
          cd packages/$MODULE

          VERSION=$(jq -r .version package.json)

          echo "Publishing commit for version $VERSION"

          git fetch
          git checkout develop
          git add .
          git commit -m "Module: $MODULE | Build mode: $BUILD_MODE | Version: $VERSION"
          git push origin develop

          git checkout main
          git merge --allow-unrelated-histories develop
          git push origin main
